version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GH_TOKEN=${GH_TOKEN}
        - BUILD=${BUILD:-latest}
        - NEXT_PUBLIC_ENV=${NEXT_PUBLIC_ENV:-production}
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # 開發環境服務
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: deps
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    profiles:
      - dev
