name: Lint Test Build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  # 可選：手動觸發
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-nextjs-
      - name: Add GITHUB_TOKEN to .npmrc
        if: ${{ env.GH_ACCESS_TOKEN != '' }}
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          npm config set //npm.pkg.github.com/:_authToken $GH_ACCESS_TOKEN
          npm config set @${{ github.repository_owner }}:registry https://npm.pkg.github.com
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
